FROM node:16.13 as server-dependencies
WORKDIR /server
COPY ./server/package.json .
RUN yarn install

FROM node:16.13 as box-universe-client
#RUN apt-get update && apt-get install libnss3-tools -y && curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64" && chmod +x mkcert-v*-linux-amd64 && cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert
WORKDIR /server
COPY ./server .
RUN mkdir -p /usr/local/share/ca-certificates/docker
RUN cp ./rootCA.pem /usr/local/share/ca-certificates/docker/ && update-ca-certificates
COPY --from=server-dependencies /server/node_modules ./node_modules
EXPOSE 2604 8000
CMD [ "yarn", "start:dev" ]
